import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Header from "../components/master/header/header";
import styles from "../styles/Home.module.scss";
import ItemList from "@components/mainMenu/mainMenu";

const Home: NextPage = () => {
  return (
    <div className={styles.home}>
      <Head>
        <title>Bar Rock - La Plata</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ItemList />
    </div>
  );
};

export default Home;
