import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/master/header/header";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={"container " + styles.home}>
      <Head>
        <title>Bar Rock - La Plata</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="row">
        <Link href="menu">
          <button className="btn btn-primary">menu</button>
        </Link>
        <Link href="musica">
          <button className="btn btn-primary">música</button>
        </Link>
        <Link href="PQR">
          <button className="btn btn-primary">
            Peticiones Quejas y Reclamos
          </button>
        </Link>
      </main>
    </div>
  );
};

export default Home;
