import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Header from "../components/layout/header/header";
import styles from "../styles/Home.module.scss";
import ItemList from "@components/home/home";

import { Container } from "semantic-ui-react";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Bar Rock - La Plata</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ItemList />
    </Container>
  );
};

export default Home;
